/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Menu;

import static Menu.BuatTagihan.rs;
import com.mysql.cj.jdbc.result.ResultSetMetaData;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.showMessageDialog;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ThinkPad
 */
public class Dashboard extends javax.swing.JFrame {
    public static Connection con;
    public static Statement stm;
    public static ResultSet res;

    /**
     * Creates new form Dashboard
     */
    public Dashboard() {
        initComponents();
        FetchPengguna();
        FetchTagihan();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpFrame = new javax.swing.JPanel();
        jpSidebar = new javax.swing.JPanel();
        sidebarDayaListrik = new javax.swing.JButton();
        sidebarPengguna = new javax.swing.JButton();
        sidebarPembayaran = new javax.swing.JButton();
        sidebarTentang = new javax.swing.JButton();
        jpMain = new javax.swing.JPanel();
        jpPengguna = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnTbhPengguna = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTablePengguna = new javax.swing.JTable();
        btnRefreshPengguna = new javax.swing.JButton();
        btnHapusPengguna = new javax.swing.JButton();
        jpTagihan = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableTagihan = new javax.swing.JTable();
        btnTagihanBuat = new javax.swing.JButton();
        tagihanRefresh = new javax.swing.JButton();
        jpPembayaran = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btnBayar = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jpTentangKami = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1200, 600));
        setPreferredSize(new java.awt.Dimension(1200, 600));

        jpFrame.setPreferredSize(new java.awt.Dimension(1200, 800));

        jpSidebar.setBackground(new java.awt.Color(0, 153, 153));
        jpSidebar.setPreferredSize(new java.awt.Dimension(250, 800));

        sidebarDayaListrik.setText("Tagihan");
        sidebarDayaListrik.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sidebarDayaListrikActionPerformed(evt);
            }
        });

        sidebarPengguna.setText("Pengguna");
        sidebarPengguna.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sidebarPenggunaActionPerformed(evt);
            }
        });

        sidebarPembayaran.setText("Pembayaran");
        sidebarPembayaran.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sidebarPembayaranActionPerformed(evt);
            }
        });

        sidebarTentang.setText("Tentang Kami");
        sidebarTentang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sidebarTentangActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpSidebarLayout = new javax.swing.GroupLayout(jpSidebar);
        jpSidebar.setLayout(jpSidebarLayout);
        jpSidebarLayout.setHorizontalGroup(
            jpSidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpSidebarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpSidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(sidebarPengguna, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(sidebarDayaListrik, javax.swing.GroupLayout.DEFAULT_SIZE, 238, Short.MAX_VALUE)
                    .addComponent(sidebarPembayaran, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(sidebarTentang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jpSidebarLayout.setVerticalGroup(
            jpSidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpSidebarLayout.createSequentialGroup()
                .addGap(86, 86, 86)
                .addComponent(sidebarDayaListrik, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(sidebarPembayaran, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(sidebarPengguna, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(sidebarTentang, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(336, Short.MAX_VALUE))
        );

        jpMain.setPreferredSize(new java.awt.Dimension(900, 550));

        jpPengguna.setBackground(new java.awt.Color(255, 255, 255));
        jpPengguna.setPreferredSize(new java.awt.Dimension(900, 550));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("Pengguna");

        btnTbhPengguna.setText("Tambah");
        btnTbhPengguna.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTbhPenggunaActionPerformed(evt);
            }
        });

        jTablePengguna.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTablePengguna.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Id", "Nama", "Telepon", "Alamat"
            }
        ));
        jScrollPane2.setViewportView(jTablePengguna);

        btnRefreshPengguna.setText("Refresh");
        btnRefreshPengguna.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshPenggunaActionPerformed(evt);
            }
        });

        btnHapusPengguna.setText("Hapus");
        btnHapusPengguna.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusPenggunaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpPenggunaLayout = new javax.swing.GroupLayout(jpPengguna);
        jpPengguna.setLayout(jpPenggunaLayout);
        jpPenggunaLayout.setHorizontalGroup(
            jpPenggunaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpPenggunaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpPenggunaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpPenggunaLayout.createSequentialGroup()
                        .addComponent(btnRefreshPengguna)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnTbhPengguna)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnHapusPengguna))
                    .addComponent(jLabel1)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 902, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jpPenggunaLayout.setVerticalGroup(
            jpPenggunaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpPenggunaLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addGap(26, 26, 26)
                .addGroup(jpPenggunaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRefreshPengguna)
                    .addComponent(btnTbhPengguna)
                    .addComponent(btnHapusPengguna))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(13, Short.MAX_VALUE))
        );

        jpTagihan.setBackground(new java.awt.Color(255, 255, 255));
        jpTagihan.setMinimumSize(new java.awt.Dimension(900, 550));
        jpTagihan.setPreferredSize(new java.awt.Dimension(900, 550));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Tagihan");

        jTableTagihan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5"
            }
        ));
        jScrollPane1.setViewportView(jTableTagihan);

        btnTagihanBuat.setText("Buat");
        btnTagihanBuat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTagihanBuatActionPerformed(evt);
            }
        });

        tagihanRefresh.setText("Refresh");
        tagihanRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tagihanRefreshActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpTagihanLayout = new javax.swing.GroupLayout(jpTagihan);
        jpTagihan.setLayout(jpTagihanLayout);
        jpTagihanLayout.setHorizontalGroup(
            jpTagihanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpTagihanLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpTagihanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 932, Short.MAX_VALUE)
                    .addGroup(jpTagihanLayout.createSequentialGroup()
                        .addGroup(jpTagihanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jpTagihanLayout.createSequentialGroup()
                                .addComponent(btnTagihanBuat)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tagihanRefresh))
                            .addComponent(jLabel2))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jpTagihanLayout.setVerticalGroup(
            jpTagihanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpTagihanLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel2)
                .addGap(29, 29, 29)
                .addGroup(jpTagihanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnTagihanBuat)
                    .addComponent(tagihanRefresh))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(61, Short.MAX_VALUE))
        );

        jpPembayaran.setBackground(new java.awt.Color(204, 204, 204));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel3.setText("Pembayaran");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(jTable1);

        btnBayar.setText("Bayar");
        btnBayar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBayarActionPerformed(evt);
            }
        });

        jButton2.setText("Refresh");

        javax.swing.GroupLayout jpPembayaranLayout = new javax.swing.GroupLayout(jpPembayaran);
        jpPembayaran.setLayout(jpPembayaranLayout);
        jpPembayaranLayout.setHorizontalGroup(
            jpPembayaranLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpPembayaranLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpPembayaranLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 932, Short.MAX_VALUE)
                    .addGroup(jpPembayaranLayout.createSequentialGroup()
                        .addGroup(jpPembayaranLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jpPembayaranLayout.createSequentialGroup()
                                .addComponent(btnBayar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton2))
                            .addComponent(jLabel3))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jpPembayaranLayout.setVerticalGroup(
            jpPembayaranLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpPembayaranLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addGap(45, 45, 45)
                .addGroup(jpPembayaranLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBayar)
                    .addComponent(jButton2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(55, Short.MAX_VALUE))
        );

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel4.setText("Tentang Kami");

        javax.swing.GroupLayout jpTentangKamiLayout = new javax.swing.GroupLayout(jpTentangKami);
        jpTentangKami.setLayout(jpTentangKamiLayout);
        jpTentangKamiLayout.setHorizontalGroup(
            jpTentangKamiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpTentangKamiLayout.createSequentialGroup()
                .addContainerGap(370, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addGap(385, 385, 385))
        );
        jpTentangKamiLayout.setVerticalGroup(
            jpTentangKamiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpTentangKamiLayout.createSequentialGroup()
                .addGap(295, 295, 295)
                .addComponent(jLabel4)
                .addContainerGap(223, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jpMainLayout = new javax.swing.GroupLayout(jpMain);
        jpMain.setLayout(jpMainLayout);
        jpMainLayout.setHorizontalGroup(
            jpMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 944, Short.MAX_VALUE)
            .addGroup(jpMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jpPengguna, javax.swing.GroupLayout.DEFAULT_SIZE, 944, Short.MAX_VALUE))
            .addGroup(jpMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jpTagihan, javax.swing.GroupLayout.DEFAULT_SIZE, 944, Short.MAX_VALUE))
            .addGroup(jpMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jpPembayaran, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jpMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jpTentangKami, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jpMainLayout.setVerticalGroup(
            jpMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(jpMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jpPengguna, javax.swing.GroupLayout.DEFAULT_SIZE, 600, Short.MAX_VALUE))
            .addGroup(jpMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jpTagihan, javax.swing.GroupLayout.DEFAULT_SIZE, 600, Short.MAX_VALUE))
            .addGroup(jpMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jpPembayaran, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jpMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jpTentangKami, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jpFrameLayout = new javax.swing.GroupLayout(jpFrame);
        jpFrame.setLayout(jpFrameLayout);
        jpFrameLayout.setHorizontalGroup(
            jpFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpFrameLayout.createSequentialGroup()
                .addComponent(jpSidebar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpMain, javax.swing.GroupLayout.DEFAULT_SIZE, 944, Short.MAX_VALUE))
        );
        jpFrameLayout.setVerticalGroup(
            jpFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpSidebar, javax.swing.GroupLayout.DEFAULT_SIZE, 600, Short.MAX_VALUE)
            .addComponent(jpMain, javax.swing.GroupLayout.DEFAULT_SIZE, 600, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpFrame, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jpFrame, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    
    private void FetchPengguna(){
        String SUrl, SUser, SPass;
        SUrl = "jdbc:mysql://localhost:3306/aplikasi_pdam";
        SUser = "root";
        SPass = "";
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            con = DriverManager.getConnection(SUrl, SUser, SPass);
            stm = con.createStatement();
            
            DefaultTableModel tb = new DefaultTableModel();
            tb.addColumn("Id");
            tb.addColumn("Nama");
            tb.addColumn("Telepon");
            tb.addColumn("Alamat");
            jTablePengguna.setModel(tb);
            
            // Mengambil data dari database
            res = stm.executeQuery("SELECT * FROM pengguna");
            while (res.next()) {
                // Memunculkan di table
                tb.addRow(new Object[]{
                    res.getString("id"),
                    res.getString("nama"),
                    res.getString("telepon"),
                    res.getString("alamat")
                });
            }   
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Data gagal ditampilkan");
        }  
    }
    
    private void FetchTagihan(){
        String SUrl, SUser, SPass;
        SUrl = "jdbc:mysql://localhost:3306/aplikasi_pdam";
        SUser = "root";
        SPass = "";
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            con = DriverManager.getConnection(SUrl, SUser, SPass);
            stm = con.createStatement();
            
            // Query Join
            String query = "SELECT tagihan.id AS id, pengguna.nama, tagihan.periode, tagihan.total_tagihan, tagihan.status " +
                       "FROM tagihan " +
                       "JOIN pengguna ON tagihan.id_pengguna = pengguna.id";
            res = stm.executeQuery(query);
            System.out.println(res);
            
            DefaultTableModel tb = new DefaultTableModel();
            tb.addColumn("ID Tagihan");
            tb.addColumn("Nama");
            tb.addColumn("Periode");
            tb.addColumn("Total Tagihan");
            tb.addColumn("Status");
            jTableTagihan.setModel(tb);
            
            // Mengambil data dari database
            while (res.next()) {
                // Memunculkan di table
                tb.addRow(new Object[]{
                    res.getString("id"),
                    res.getString("nama"),
                    res.getString("periode"),
                    res.getString("total_tagihan"),
                    res.getString("status"),
                });
            }   
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error: " + e.getMessage());
        }   finally {
            // Menutup Resource
            try {
                if (res != null) res.close();
                if (stm != null) stm.close();
                if (con != null) con.close();
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(null, "Error saat menutup koneksi: " + ex.getMessage());
            }
        }
    }
    
    private void sidebarDayaListrikActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sidebarDayaListrikActionPerformed
        // TODO add your handling code here:
        jpMain.removeAll();
        jpMain.repaint();
        jpMain.revalidate();
        
        // pindah panel
        jpMain.add(jpTagihan);
        jpMain.repaint();
        jpMain.revalidate();
    }//GEN-LAST:event_sidebarDayaListrikActionPerformed

    private void sidebarPenggunaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sidebarPenggunaActionPerformed
        // TODO add your handling code here:
        jpMain.removeAll();
        jpMain.repaint();
        jpMain.revalidate();
        
        // pindah panel
        jpMain.add(jpPengguna);
        jpMain.repaint();
        jpMain.revalidate();
    }//GEN-LAST:event_sidebarPenggunaActionPerformed


    
    private void btnTbhPenggunaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTbhPenggunaActionPerformed
        // TODO add your handling code here:
        TambahPengguna TambahPenggunaFrame = new TambahPengguna();
        TambahPenggunaFrame.setVisible(true);
    }//GEN-LAST:event_btnTbhPenggunaActionPerformed

    private void btnRefreshPenggunaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshPenggunaActionPerformed
        // TODO add your handling code here:
        FetchPengguna();
    }//GEN-LAST:event_btnRefreshPenggunaActionPerformed

    private void btnHapusPenggunaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusPenggunaActionPerformed
        // TODO add your handling code here:
        String SUrl, SUser, SPass;
        SUrl = "jdbc:mysql://localhost:3306/aplikasi_pdam";
        SUser = "root";
        SPass = "";
        try{
            Class.forName("com.mysql.cj.jdbc.Driver");
            con = DriverManager.getConnection(SUrl, SUser, SPass);
            stm = con.createStatement();
            
            int a = jTablePengguna.getSelectedRow();
            String id = jTablePengguna.getValueAt(a, 0).toString();
            String query = "DELETE FROM pengguna WHERE id='"+id+"'";
            stm.executeUpdate(query);
            FetchPengguna();
        } catch (Exception e) {
            System.out.println("Data Gagal Dihapus");
        }
    }//GEN-LAST:event_btnHapusPenggunaActionPerformed

    private void btnTagihanBuatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTagihanBuatActionPerformed
        // TODO add your handling code here:
        BuatTagihan BuatTagihanFrame = new BuatTagihan();
        BuatTagihanFrame.setVisible(true);
    }//GEN-LAST:event_btnTagihanBuatActionPerformed

    private void sidebarPembayaranActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sidebarPembayaranActionPerformed
        // TODO add your handling code here:
                // TODO add your handling code here:
        jpMain.removeAll();
        jpMain.repaint();
        jpMain.revalidate();
        
        // pindah panel
        jpMain.add(jpPembayaran);
        jpMain.repaint();
        jpMain.revalidate();
    }//GEN-LAST:event_sidebarPembayaranActionPerformed

    private void sidebarTentangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sidebarTentangActionPerformed
        // TODO add your handling code here:
                // TODO add your handling code here:
        jpMain.removeAll();
        jpMain.repaint();
        jpMain.revalidate();
        
        // pindah panel
        jpMain.add(jpTentangKami);
        jpMain.repaint();
        jpMain.revalidate();
    }//GEN-LAST:event_sidebarTentangActionPerformed

    private void tagihanRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tagihanRefreshActionPerformed
        // TODO add your handling code here:
        FetchTagihan();
    }//GEN-LAST:event_tagihanRefreshActionPerformed

    private void btnBayarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBayarActionPerformed
        // TODO add your handling code here:
        Pembayaran PembayaranFrame = new Pembayaran();
        PembayaranFrame.setVisible(true);
    }//GEN-LAST:event_btnBayarActionPerformed

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Dashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBayar;
    private javax.swing.JButton btnHapusPengguna;
    private javax.swing.JButton btnRefreshPengguna;
    private javax.swing.JButton btnTagihanBuat;
    private javax.swing.JButton btnTbhPengguna;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTablePengguna;
    private javax.swing.JTable jTableTagihan;
    private javax.swing.JPanel jpFrame;
    private javax.swing.JPanel jpMain;
    private javax.swing.JPanel jpPembayaran;
    private javax.swing.JPanel jpPengguna;
    private javax.swing.JPanel jpSidebar;
    private javax.swing.JPanel jpTagihan;
    private javax.swing.JPanel jpTentangKami;
    private javax.swing.JButton sidebarDayaListrik;
    private javax.swing.JButton sidebarPembayaran;
    private javax.swing.JButton sidebarPengguna;
    private javax.swing.JButton sidebarTentang;
    private javax.swing.JButton tagihanRefresh;
    // End of variables declaration//GEN-END:variables
}
